### PR TITLE
feat(app): swap timestamp display

### PR DESCRIPTION
**Pull request by c43721**
First of all, thank you for your contribution! 😄

Please make sure you have read [contribution guidelines](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#before-contributing). 

### Most important items

- Make sure to communicate your proposed changes ob our Slack channel beforehand.
- Large PRs (50+ lines of code) will get rejected due to increased difficulty for review - unless they have been communicated beforehand with project maintainers.
- **Refactoring work will get rejected** unless it's been communicated with project's maintainers **beforehand**. There is a thousand ways to write the same code. Every time a code is changed, there is a potential for a new bug. We don't want to refactor the code just for the sake of refactoring.

These rules are strictly enforced to make sure that we can maintain the project moving forward. 

These deps should never be in a project's dependencies, as they're used for development only. Move them accordingly to allow for package manager to purge non-essential packages from our project.

~~This PR builds on #98, please merge that first before merging this. It'll need a rebase but that's fine.~~

This swaps the timestamps so that you can see a friendly version up front, and hover for details. This is a UX improvement.
image

(A Day Ago would display on the table and the full date in the tooltip)

### CODE REVIEW

**Comment by c43721** [comment]
oh this needs a rebase now :O

**Comment by githubsaturn** [comment]
I don't necessarily believe this is a better UX. The timestamp doesn't get updated while staying on this page. So it'll keep saying "a few seconds ago". The issue is the same with tooltips, but at least it's a secondary component and it's not directly visible on screen. 

But I am not strictly against this. So please feel free to run it as a quick poll in the Slack channel so that people can :+1:  or :-1: and we'll see if it's a good thing or not.

**Comment by c43721** [comment]
I think that can be solved, either in this pr or a follow up, where we can just have a timer running and update the timestamp every 5 seconds or so. That would be the best compromise.

I will send the poll.

**Comment by LiquidITGuy** [comment]
I'm interested of the expected behaviour to replace moment by date fns

**Comment by githubsaturn** [comment]
@LiquidITGuy - sorry I forgot to close this PR. We sent a poll a while ago, and majority of users voted to keep the current UX.

**Pull request closed without merging**
