### PR TITLE
use arrow functions

### PR DESCRIPTION
**Pull request by ManAnRuck**
prefer arrow functions instead of assigning a variable self.

Bildschirmfoto 2019-08-29 um 07 17 07

Node: npm test was running successful, ~but until now not tested in usage~ with local backend too :)

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks for your contribution, but this is the styling that we have adopted throughout the project. We'll stick with our current styling.

**Comment by ManAnRuck** [comment]
sure :)

but I have a question just for understanding.
1. there are currently also a lot of arrow functions. so both styles are existing. 
which do you prefer?

2. is there any specific reason to use the `self = this` style or just out of habit?

**Comment by githubsaturn** [comment]
1) There are a few arrow functions, but mostly for promises, which is majority of this change, we use `self`.

2) In JavaScript, naturally in TypeScript, there are a million different ways to do the same thing, usually they have no advantage and disadvantage against each other. Test coverage for this project is very minimal, therefore, changing a massive amount of code is only justified if it has to be done to support a feature or fix a bug. 


Last but definitely not least, there are multiple easy to tackle issues, that you can tackle if you'r interested in contributing to the front-end project :) 
https://github.com/caprover/caprover-frontend/issues

**Comment by ManAnRuck** [comment]
okay :) test coverage is a massive argument! totally agree

just to explain my investigation: this self style comes to me from the time before there were arrow functions.  (I still agree your argument ;) )

i want to have a look into the other issues to support this project :)

just one idea to help contributing this project. (perhaps wrong place here, we can continue in slack if you want)
a label, that a bug is confirmed would help to tackle, this in reason of "its a feature not a bug" 😇
like here (https://github.com/prisma/prisma2/issues?q=is%3Aissue+is%3Aopen+label%3Abug%2F2-confirmed)

**Comment by githubsaturn** [comment]
We use labels extensively in the main backend repo, but the front repo is a second class citizen unfortunately. I just added a bunch of new labels to the issues here in the frontend code. Hope it helps.

**Pull request closed without merging**
